name: SonarCloud Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    name: Run SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install Sonar Scanner
        run: |
          dotnet tool install --global dotnet-sonarscanner

      - name: Run SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          export PATH="$PATH:$HOME/.dotnet/tools"
          dotnet sonarscanner begin \
            /k:"tomasyoel_lab01u2tomasyoelweb" \
            /o:"tomasyoel" \
            /d:sonar.login=$SONAR_TOKEN
          dotnet build || true
          dotnet sonarscanner end /d:sonar.login=$SONAR_TOKEN

      - name: Upload SonarCloud Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sonarcloud-results
          path: .sonarqube/out/.sonar/*.json
