name: TfSec Scan

on:
  push:
    branches:
      - main 
    paths:
      - '**' 
  pull_request:
    branches:
      - main 

jobs:
  tfsec-scan:
    name: Run TfSec Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install TfSec
        run: |
          curl -L -o tfsec https://github.com/aquasecurity/tfsec/releases/latest/download/tfsec-linux-amd64
          chmod +x tfsec
          mv tfsec /usr/local/bin/

      - name: Run TfSec
        run: |
          tfsec --format json --out tfsec-report.json || echo "tfsec completed with warnings/errors"

      - name: Upload TfSec Report
        uses: actions/upload-artifact@v4
        with:
          name: tfsec-report
          path: tfsec-report.json
